server.event_handler("intermission", function()
    local f = io.open("stats.txt", "a")
    f:write("--[[ Automatically generated by HaythServ, do not edit! ]]--\n")
    f:write(string.format("--[[ %s ]]--\n", os.date("%c")))
    f:write("--[[ Name Frags Deaths Teamkills Accuracy ]]--\n")
    for p in server.gclients() do
        f:write(string.format("%s %i %i %i %i\n", p:name(), p:frags(), p:deaths(), p:teamkills(), p:accuracy()))
    end
    f:close()
end)
